-- MySQL Script generated by MySQL Workbench
-- Sat Sep 28 15:48:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema despesas-receitas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema despesas-receitas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `despesas-receitas` ;
USE `despesas-receitas` ;

-- -----------------------------------------------------
-- Table `despesas-receitas`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `despesas-receitas`.`categorias` (
  `id_categorias` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `despesas-receitas`.`transacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `despesas-receitas`.`transacoes` (
  `id_transacoes` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `valor` FLOAT NULL,
  `data` DATE NULL,
  `categoria_id` INT NULL,
  PRIMARY KEY (`id_transacoes`),
  INDEX `fk_transacoes_categoria_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_transacoes_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `despesas-receitas`.`categorias` (`id_categorias`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `despesas-receitas`.`categorias`
-- -----------------------------------------------------
START TRANSACTION;
USE `despesas-receitas`;
INSERT INTO `despesas-receitas`.`categorias` (`id_categorias`, `nome`) VALUES (DEFAULT, 'Alimentação');
INSERT INTO `despesas-receitas`.`categorias` (`id_categorias`, `nome`) VALUES (DEFAULT, 'Transporte');
INSERT INTO `despesas-receitas`.`categorias` (`id_categorias`, `nome`) VALUES (DEFAULT, 'Compras');
INSERT INTO `despesas-receitas`.`categorias` (`id_categorias`, `nome`) VALUES (DEFAULT, 'Serviços');

COMMIT;


-- -----------------------------------------------------
-- Data for table `despesas-receitas`.`transacoes`
-- -----------------------------------------------------
START TRANSACTION;
USE `despesas-receitas`;
INSERT INTO `despesas-receitas`.`transacoes` (`id_transacoes`, `tipo`, `descricao`, `valor`, `data`, `categoria_id`) VALUES (DEFAULT, 'despesa', 'Compra de supermercado', 150, '2024-09-28', 1);
INSERT INTO `despesas-receitas`.`transacoes` (`id_transacoes`, `tipo`, `descricao`, `valor`, `data`, `categoria_id`) VALUES (DEFAULT, 'receita', 'Salário', 2500, '2024-09-28', NULL);
INSERT INTO `despesas-receitas`.`transacoes` (`id_transacoes`, `tipo`, `descricao`, `valor`, `data`, `categoria_id`) VALUES (DEFAULT, 'despesa', 'Compra de roupas', 100, '2024-09-29', 3);
INSERT INTO `despesas-receitas`.`transacoes` (`id_transacoes`, `tipo`, `descricao`, `valor`, `data`, `categoria_id`) VALUES (DEFAULT, 'despesa', 'Manutenção do carro', 200, '2024-09-30', 4);
INSERT INTO `despesas-receitas`.`transacoes` (`id_transacoes`, `tipo`, `descricao`, `valor`, `data`, `categoria_id`) VALUES (DEFAULT, 'receita', 'Freelance', 1000, '2024-09-30', NULL);

COMMIT;

